name: Tests

on:
  push:
    paths: '**.py'
    branches: [ "main", "dev" ]
  pull_request:
    paths: '**.py'
    branches: [ "main", "dev" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Automatic test
      run: python autopwn.py -y -t 127.0.0.1